version: '2'
services:
  jhipsterligmotoru2-app:
    image: jhipsterligmotoru2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterligmotoru2-postgresql:5432/jhipsterLigMotoru2
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipsterligmotoru2-postgresql:
    extends:
      file: postgresql.yml
      service: jhipsterligmotoru2-postgresql
